[project]
name = "repl-nix-tomographywebappmvp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "h5py>=3.12.1",
    "numpy>=2.1.3",
    "pillow>=11.0.0",
    "streamlit>=1.40.2",
    "tifffile>=2024.9.20",
    "tomopy>=1.10.3",
]
